apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels:
    app: guestbook-ui
spec:
  selector:
    app: guestbook-ui
  ports:
    - port: 8010
      targetPort: 8000
      protocol: TCP
